/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.Controlador_FRM_MantenimientoCursos;

public class FRM_MantenimientoCursos extends javax.swing.JFrame {
Controlador_FRM_MantenimientoCursos controlador_FRM_MantenimientoCursos;
    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public FRM_MantenimientoCursos()//MetodoConstructor.
    {
        initComponents();
        setVisible(false);
        setLocation(270,130);
        controlador_FRM_MantenimientoCursos=new Controlador_FRM_MantenimientoCursos(this);
        gUI_BotonesCurso1.agregarEvento(controlador_FRM_MantenimientoCursos);
    }

    public String[] devolverInformacionCurso()//Metodo.
    {
        return this.gUI_InformacionCurso1.devolverInformacion();
    }
      
    
     public void mostrarInformacion(String arreglo[])//Metodo.
    {
     this.gUI_InformacionCurso1.mostrarInformacion(arreglo);
    }
       public void mostrarInformacionTodo(String mensaje)//Metodo 
    {     
        this.gUI_BotonesCurso1.mostrarInformacionTodos(mensaje);
    }
    
    
       
       
       
     public void mostrarInformacionJtArea(String arreglo[])//Metodo.
    {
        
        this.gUI_BotonesCurso1.mostrarInformacion(arreglo);
    }
   
     public String devolverSiglasCurso()//Metodo.
    {
    return this.gUI_InformacionCurso1.devolverSiglasCurso();
    }
     
     
     public void limpiarInformacionJtArea(String arreglo[])
    {
        this.gUI_BotonesCurso1.limpiarInformacionJtArea(arreglo);
    }
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCurso1 = new Vista.GUI_InformacionCurso();
        gUI_BotonesCurso1 = new Vista.GUI_BotonesCurso();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(gUI_BotonesCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gUI_InformacionCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_InformacionCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(gUI_BotonesCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesCurso gUI_BotonesCurso1;
    private Vista.GUI_InformacionCurso gUI_InformacionCurso1;
    // End of variables declaration//GEN-END:variables
}
