/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.Controlador_FRM_MantenimientoEstudiantes;//Importacion del controlador.

public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoEstudiante
     */
    Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;//Instancia del controlador.

    public FRM_MantenimientoEstudiantes() //METODO COSTRUCTOR.
    {
        initComponents();
        setVisible(false);
        setLocation(270, 130);
        controlador_FRM_MantenimientoEstudiantes = new Controlador_FRM_MantenimientoEstudiantes(this);
        gUI_BotonesEstudiante1.agregarEvento(controlador_FRM_MantenimientoEstudiantes); //Esta en el paquete vista.
    }

    public String[] devolverInformacion()//Metodo.
    {
        return this.gUI_InformacionEstudiante1.devolverInformacion();
    }

    public void mostrarInformacion(String arreglo[])//Metodo.
    {
        this.gUI_InformacionEstudiante1.mostrarInformacion(arreglo);
        this.gUI_BotonesEstudiante1.mostrarInformacion(arreglo);
    }
   
    
    
     public void mostrarInformacionTodo(String mensaje)//Metodo.
    {     
        this.gUI_BotonesEstudiante1.mostrarInformacionTodos(mensaje);
    }
    
    
    public void limpiarInformacionJtArea(String arreglo[])
    {
        this.gUI_BotonesEstudiante1.limpiarInformacionJtArea(arreglo);
    }
  
   
    
    public void mostrarInformacionJtArea(String arreglo[])//Metodo.
    {
        
        this.gUI_BotonesEstudiante1.mostrarInformacion(arreglo);
    }

    public String devolverCarnet()//Metodo.
    {
        return this.gUI_InformacionEstudiante1.devolverCarnet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_BotonesEstudiante1 = new Vista.GUI_BotonesEstudiante();
        gUI_InformacionEstudiante1 = new Vista.GUI_InformacionEstudiante();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_BotonesEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_BotonesEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_BotonesEstudiante gUI_BotonesEstudiante1;
    private Vista.GUI_InformacionEstudiante gUI_InformacionEstudiante1;
    // End of variables declaration//GEN-END:variables
}
