/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.Controlador_FRM_MantenimientoCursos;//Importacion de la claseControlador.

public class GUI_BotonesCurso extends javax.swing.JPanel {
Controlador_FRM_MantenimientoCursos controlador;//Instancia de la clase controlador.
    /**
     * Creates new form GUI_BotonesCursos
     */
   
public GUI_BotonesCurso() //MetodoConstructor.
    {
        initComponents();  
    }
   
     public void mostrarInformacion(String  arreglo[])///muestra en el jTextNombre
    {
        this.jtArea_InformacionCurso.setText("Siglas del Curso: "+arreglo[0]+"\nNombre del Curso: "+arreglo[1]+"\nCréditos del Curso"+arreglo[2]);  
    }
     public void limpiarInformacionJtArea(String  arreglo[])///muestra en el jTextNombre
    {
        this.jtArea_InformacionCurso.setText("Estudiante Eliminado");  
    }
        public void mostrarInformacionTodos(String  mensaje)///muestra en el jText de todos los nombres y carnet de los estudiantes
    {
        this.jtArea_InformacionCurso.setText(mensaje);  
    }
    
    public void agregarEvento(Controlador_FRM_MantenimientoCursos controlador)
    {
    this.controlador=controlador;
    this.btn_AgregarCurso.addActionListener(controlador);
    this.btn_ConsultarCurso.addActionListener(controlador);
    this.btn_ModificarCurso.addActionListener(controlador);
    this.btn_EliminarCurso.addActionListener(controlador);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_AgregarCurso = new javax.swing.JToggleButton();
        btn_ConsultarCurso = new javax.swing.JToggleButton();
        btn_ModificarCurso = new javax.swing.JToggleButton();
        btn_EliminarCurso = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArea_InformacionCurso = new javax.swing.JTextArea();

        btn_AgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarCurso.png"))); // NOI18N
        btn_AgregarCurso.setActionCommand("AgregarCurso");
        btn_AgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarCursoActionPerformed(evt);
            }
        });

        btn_ConsultarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultarCurso.png"))); // NOI18N
        btn_ConsultarCurso.setActionCommand("ConsultarCurso");
        btn_ConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarCursoActionPerformed(evt);
            }
        });

        btn_ModificarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificarCurso.png"))); // NOI18N
        btn_ModificarCurso.setActionCommand("ModificarCurso");

        btn_EliminarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarCurso.png"))); // NOI18N
        btn_EliminarCurso.setActionCommand("EliminarCurso");

        jtArea_InformacionCurso.setColumns(20);
        jtArea_InformacionCurso.setRows(5);
        jScrollPane1.setViewportView(jtArea_InformacionCurso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_AgregarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ConsultarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ModificarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btn_EliminarCurso)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_AgregarCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ConsultarCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ModificarCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_EliminarCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarCursoActionPerformed

    private void btn_ConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConsultarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_AgregarCurso;
    private javax.swing.JToggleButton btn_ConsultarCurso;
    private javax.swing.JToggleButton btn_EliminarCurso;
    private javax.swing.JToggleButton btn_ModificarCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtArea_InformacionCurso;
    // End of variables declaration//GEN-END:variables
}
